import { describe, expect, test } from "bun:test"
import { Effect, Layer } from "effect"
import { Database } from "@opencode-ai/core/database/database"
import { FSUtil } from "@opencode-ai/core/fs-util"
import { tmpdir } from "../fixture/tmpdir"
import path from "path"
import fs from "fs/promises"
import { CodegraphIndexer } from "../../src/banyancode/codegraph-indexer"
import { CodegraphRepo, defaultLayer as codegraphRepoDefaultLayer } from "../../src/banyancode/codegraph-repo"

process.env.BANYANCODE_ENABLE = "1"

describe("CodegraphIndexer extra kinds", () => {
  test("indexes all kinds: test, route, config, docker, generated", async () => {
    await using tmp = await tmpdir()
    const dbPath = path.join(tmp.path, "test.sqlite")
    const dbLayer = Database.layerFromPath(dbPath)

    // Create a fixture with one of each kind
    await fs.writeFile(
      path.join(tmp.path, "app.test.ts"),
      `describe("Auth", () => {
  it("logs in", () => { expect(true).toBe(true) })
})`,
    )
    await fs.writeFile(
      path.join(tmp.path, "app.ts"),
      `function handleFoo(req: Request): Response { return new Response("ok") }
app.get("/foo", handleFoo)`,
    )
    await fs.writeFile(path.join(tmp.path, "package.json"), JSON.stringify({ name: "test-pkg", version: "0.1.0" }, null, 2))
    await fs.writeFile(path.join(tmp.path, "config.json"), JSON.stringify({ debug: true }))
    await fs.writeFile(path.join(tmp.path, "Dockerfile"), "FROM node:20\n")
    await fs.writeFile(
      path.join(tmp.path, "autogen.ts"),
      `// Code generated by script — DO NOT EDIT
export const value = 42`,
    )

    const serviceLayer = CodegraphIndexer.layer.pipe(
      Layer.provide(FSUtil.defaultLayer),
      Layer.provide(codegraphRepoDefaultLayer),
    )

    await Effect.runPromise(
      Effect.gen(function* () {
        const indexer = yield* CodegraphIndexer.Service
        const repo = yield* CodegraphRepo.Service

        yield* indexer.index({ root: tmp.path })

        const nodes = yield* repo.listAllNodes()
        const kinds = nodes.map((n) => n.kind)

        expect(kinds.filter((k) => k === "test").length).toBeGreaterThanOrEqual(1)
        expect(kinds.filter((k) => k === "route").length).toBeGreaterThanOrEqual(1)
        expect(kinds.filter((k) => k === "config").length).toBeGreaterThanOrEqual(2)
        expect(kinds.filter((k) => k === "docker").length).toBeGreaterThanOrEqual(1)
        expect(kinds.filter((k) => k === "generated").length).toBeGreaterThanOrEqual(1)
      }).pipe(
        Effect.provide(serviceLayer),
        Effect.provide(codegraphRepoDefaultLayer),
        Effect.provide(dbLayer),
        Effect.scoped,
      ),
    )
  })

  test("tested_by edge: source node is tested_by its test node", async () => {
    await using tmp = await tmpdir()
    const dbPath = path.join(tmp.path, "test.sqlite")
    const dbLayer = Database.layerFromPath(dbPath)

    // A source file with a named function
    await fs.writeFile(path.join(tmp.path, "math.ts"), "export function add(a: number, b: number): number { return a + b }")
    // A test file that references the function by name
    await fs.writeFile(
      path.join(tmp.path, "math.test.ts"),
      `import { add } from "./math"
it("adds two numbers", () => { expect(add(1, 2)).toBe(3) })`,
    )

    const serviceLayer = CodegraphIndexer.layer.pipe(
      Layer.provide(FSUtil.defaultLayer),
      Layer.provide(codegraphRepoDefaultLayer),
    )

    await Effect.runPromise(
      Effect.gen(function* () {
        const indexer = yield* CodegraphIndexer.Service
        const repo = yield* CodegraphRepo.Service

        yield* indexer.index({ root: tmp.path })

        const edges = yield* repo.listAllEdges()
        const testedByEdges = edges.filter((e) => e.kind === "tested_by")
        expect(testedByEdges.length).toBeGreaterThanOrEqual(1)
      }).pipe(
        Effect.provide(serviceLayer),
        Effect.provide(codegraphRepoDefaultLayer),
        Effect.provide(dbLayer),
        Effect.scoped,
      ),
    )
  })

  test("configured_by edge: source file connects to package.json in same directory", async () => {
    await using tmp = await tmpdir()
    const dbPath = path.join(tmp.path, "test.sqlite")
    const dbLayer = Database.layerFromPath(dbPath)

    await fs.writeFile(path.join(tmp.path, "package.json"), JSON.stringify({ name: "my-proj" }))
    await fs.mkdir(path.join(tmp.path, "src"), { recursive: true })
    await fs.writeFile(path.join(tmp.path, "src", "package.json"), JSON.stringify({ name: "my-proj-src" }))
    await fs.writeFile(path.join(tmp.path, "src", "index.ts"), 'import pkg from "./package.json"\nexport function x() { return pkg.name }')

    const serviceLayer = CodegraphIndexer.layer.pipe(
      Layer.provide(FSUtil.defaultLayer),
      Layer.provide(codegraphRepoDefaultLayer),
    )

    await Effect.runPromise(
      Effect.gen(function* () {
        const indexer = yield* CodegraphIndexer.Service
        const repo = yield* CodegraphRepo.Service

        yield* indexer.index({ root: tmp.path })

        const edges = yield* repo.listAllEdges()
        const configuredByEdges = edges.filter((e) => e.kind === "configured_by")
        expect(configuredByEdges.length).toBeGreaterThanOrEqual(1)
      }).pipe(
        Effect.provide(serviceLayer),
        Effect.provide(codegraphRepoDefaultLayer),
        Effect.provide(dbLayer),
        Effect.scoped,
      ),
    )
  })

  test("built_by edge: package.json connects to Dockerfile", async () => {
    await using tmp = await tmpdir()
    const dbPath = path.join(tmp.path, "test.sqlite")
    const dbLayer = Database.layerFromPath(dbPath)

    await fs.writeFile(path.join(tmp.path, "package.json"), JSON.stringify({ name: "my-proj" }))
    await fs.writeFile(path.join(tmp.path, "Dockerfile"), "FROM node:20\n")

    const serviceLayer = CodegraphIndexer.layer.pipe(
      Layer.provide(FSUtil.defaultLayer),
      Layer.provide(codegraphRepoDefaultLayer),
    )

    await Effect.runPromise(
      Effect.gen(function* () {
        const indexer = yield* CodegraphIndexer.Service
        const repo = yield* CodegraphRepo.Service

        yield* indexer.index({ root: tmp.path })

        const edges = yield* repo.listAllEdges()
        const builtByEdges = edges.filter((e) => e.kind === "built_by")
        expect(builtByEdges.length).toBeGreaterThanOrEqual(1)
      }).pipe(
        Effect.provide(serviceLayer),
        Effect.provide(codegraphRepoDefaultLayer),
        Effect.provide(dbLayer),
        Effect.scoped,
      ),
    )
  })

  test("mounts edge: route node mounts its handler function", async () => {
    await using tmp = await tmpdir()
    const dbPath = path.join(tmp.path, "test.sqlite")
    const dbLayer = Database.layerFromPath(dbPath)

    await fs.writeFile(
      path.join(tmp.path, "app.ts"),
      `function myHandler(req: Request): Response { return new Response("ok") }
app.get("/hello", myHandler)`,
    )

    const serviceLayer = CodegraphIndexer.layer.pipe(
      Layer.provide(FSUtil.defaultLayer),
      Layer.provide(codegraphRepoDefaultLayer),
    )

    await Effect.runPromise(
      Effect.gen(function* () {
        const indexer = yield* CodegraphIndexer.Service
        const repo = yield* CodegraphRepo.Service

        yield* indexer.index({ root: tmp.path })

        const edges = yield* repo.listAllEdges()
        const mountsEdges = edges.filter((e) => e.kind === "mounts")
        expect(mountsEdges.length).toBeGreaterThanOrEqual(1)
      }).pipe(
        Effect.provide(serviceLayer),
        Effect.provide(codegraphRepoDefaultLayer),
        Effect.provide(dbLayer),
        Effect.scoped,
      ),
    )
  })

  test("generated_from edge: generated file links to its source", async () => {
    await using tmp = await tmpdir()
    const dbPath = path.join(tmp.path, "test.sqlite")
    const dbLayer = Database.layerFromPath(dbPath)

    await fs.writeFile(path.join(tmp.path, "foo.ts"), "export function foo() { return 1 }")
    await fs.writeFile(
      path.join(tmp.path, "foo.generated.ts"),
      `// Code generated by script
export const foo = 1`,
    )

    const serviceLayer = CodegraphIndexer.layer.pipe(
      Layer.provide(FSUtil.defaultLayer),
      Layer.provide(codegraphRepoDefaultLayer),
    )

    await Effect.runPromise(
      Effect.gen(function* () {
        const indexer = yield* CodegraphIndexer.Service
        const repo = yield* CodegraphRepo.Service

        yield* indexer.index({ root: tmp.path })

        const edges = yield* repo.listAllEdges()
        const generatedFromEdges = edges.filter((e) => e.kind === "generated_from")
        expect(generatedFromEdges.length).toBeGreaterThanOrEqual(1)
      }).pipe(
        Effect.provide(serviceLayer),
        Effect.provide(codegraphRepoDefaultLayer),
        Effect.provide(dbLayer),
        Effect.scoped,
      ),
    )
  })

  test("WS-D new kinds: doc, docker, ci, env, config classify the right files", async () => {
    await using tmp = await tmpdir()
    const dbPath = path.join(tmp.path, "test.sqlite")
    const dbLayer = Database.layerFromPath(dbPath)

    await fs.writeFile(path.join(tmp.path, "README.md"), "# Title\n\nIntro paragraph.\n")
    await fs.writeFile(path.join(tmp.path, "CHANGELOG.md"), "## v0.1.0\n- Initial release\n")
    await fs.writeFile(
      path.join(tmp.path, "Dockerfile"),
      "FROM node:20\nRUN npm ci\nCMD [\"node\", \"index.js\"]\n",
    )
    await fs.mkdir(path.join(tmp.path, ".github", "workflows"), { recursive: true })
    await fs.writeFile(
      path.join(tmp.path, ".github", "workflows", "ci.yml"),
      "name: ci\non: push\njobs:\n  test:\n    runs-on: ubuntu-latest\n",
    )
    await fs.writeFile(path.join(tmp.path, "package.json"), JSON.stringify({ name: "demo", version: "0.1.0" }))
    await fs.writeFile(path.join(tmp.path, ".env.example"), "FOO=bar\n")
    await fs.writeFile(path.join(tmp.path, "tsconfig.json"), JSON.stringify({ compilerOptions: { strict: true } }))
    await fs.writeFile(
      path.join(tmp.path, "compose.yml"),
      "services:\n  web:\n    image: nginx\n",
    )

    const serviceLayer = CodegraphIndexer.layer.pipe(
      Layer.provide(FSUtil.defaultLayer),
      Layer.provide(codegraphRepoDefaultLayer),
    )

    await Effect.runPromise(
      Effect.gen(function* () {
        const indexer = yield* CodegraphIndexer.Service
        const repo = yield* CodegraphRepo.Service

        yield* indexer.index({ root: tmp.path })

        const nodes = yield* repo.listAllNodes()
        const files = yield* repo.listAllFiles()
        const fileByPath = new Map(files.map((f) => [f.path.replace(/\\/g, "/"), f]))

        const nodesFor = (relPath: string) => {
          const file = fileByPath.get(path.join(tmp.path, relPath).replace(/\\/g, "/"))
          if (!file) return []
          return nodes.filter((n) => n.fileID === file.id)
        }

        expect(nodesFor("README.md").some((n) => n.kind === "doc")).toBe(true)
        expect(nodesFor("CHANGELOG.md").some((n) => n.kind === "doc")).toBe(true)
        expect(nodesFor("Dockerfile").some((n) => n.kind === "docker")).toBe(true)
        expect(nodesFor("Dockerfile").filter((n) => n.kind === "docker").length).toBeGreaterThanOrEqual(2)
        expect(nodesFor("compose.yml").some((n) => n.kind === "docker")).toBe(true)
        expect(nodesFor(".github/workflows/ci.yml").some((n) => n.kind === "ci")).toBe(true)
        expect(nodesFor(".env.example").some((n) => n.kind === "env")).toBe(true)
        expect(nodesFor("package.json").some((n) => n.kind === "config")).toBe(true)
        expect(nodesFor("tsconfig.json").some((n) => n.kind === "config")).toBe(true)
      }).pipe(
        Effect.provide(serviceLayer),
        Effect.provide(codegraphRepoDefaultLayer),
        Effect.provide(dbLayer),
        Effect.scoped,
      ),
    )
  })
})
